version: "3.7"
services:
  mainserver:
    image: main-server
    container_name: mainserver
    build:
      context: ./mainserver
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SERVER_PORT: 3002
      DB_NAME_SQL: Uno
      DB_USERNAME_SQL: root
      DB_PASSWORD_SQL: 12345678
      DB_HOST_SQL: mysql
      SESSION_SECRET: Its 322
      SECRET_KEY: It's easy 322
    links:
      - mysql
    ports:
      - 3002:3002
    volumes:
      - ./static/productImages:/app/mainserver/static/productImages
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
  mysql:
    container_name: mysql
    image: mysql
    restart: on-failure
    command:  --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: Uno
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 33061:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
